### PR TITLE
Significant changes to on-save syntax checking.

### PR DESCRIPTION
**Pull request by ehuss**
This is an experiment I was messing around with to improve the on-save error checking.

- Crates with multiple targets are automatically detected.
- Highlight/outline the regions where the message is.
- Include a link for Exxxx errors to a web page.
- Include a way to close/hide messages.
- Support non-ascii output on certain platforms.
- Display more messages (notes, macro expansions, etc.)
- If there is a message for a file not currently open, print it to the console.

re2
re1

I can break some of these changes into separate PRs if you'd like, though they all touch the same code so that might be a little tricky.

### CODE REVIEW

**Comment by Jayflux** [comment]
@ehuss could i ask you update the readme with the changes you have made, so we keep it up to date with what this package can do.

Whats the error_tests folder?

**Comment by ehuss** [comment]
Sure, I can update it.  I just wanted to get some feedback to see if you are interested in the changes before putting in more work.

The error_tests includes some samples that exercise some of the more esoteric messages (like macro expansion, refactoring tips, etc.).  Currently I just manually go through the files and hit save on each one and check what it looks like.  I thought about creating some automated tests, but that would be some work to mock the sublime API.

**Comment by dten** [comment]
Tried this out and it's pretty sweet :)!

**Comment by Jayflux** [comment]
@ehuss looks good, ive played around with it, happy to merge something like this, but will let you carry on if there's more work to do

**Comment by dten** [comment]
been trying this some more.

one of my projects can be compiled as --bin or --lib and i find it duplicates some warnings such as below
image

I also have a build script and am seeing this in the log
`Failed to run: cargo rustc --custom-build build-script-build -- -Zno-trans -Zunstable-options --error-format=json`

**Comment by ehuss** [comment]
The automatic target detection needs some work.  I'm going to change it to be a little smarter.  

If you want some background, see flycheck/flycheck-rust/pull/43 and rust-lang/cargo/issues/3211.  I looked at `rustc --emit dep-info` a little, but it is finicky.  I think I will do something similar to what that PR for flycheck-rust does.

**Comment by dten** [comment]
might be nice if it were optional also. 

personally my bin target just calls the lib with some args and so it's 99.9% lib. building all targets makes the checks take 6+ seconds instead of about 3, and sometimes building the bin goes crazy and takes 10s of seconds.

**Comment by Jayflux** [comment]
@ehuss any update on this? You mentioned needing more time to make changes

**Comment by ehuss** [comment]
I've been using the latest version for a while, and it seems to be working well for me.  I was updating the README and was wondering how you prefer to host images.  The options I've seen:
* Place file directly in repo, with a relative link (raw=true).  Downside it slightly bloats the repo.
* Put it in a separate "images" branch.
* Place image in an Issue and use the link generated from that.

This is the image I was thinking of using (not sure if you would prefer an animated one or not).
syntax1

**Comment by Jayflux** [comment]
@ehuss good question, up to this point i've been using images hosted from the issue (like what you have done there).
I don't know for sure how long they stay hosted (maybe it's something i should find out).
I'm not too bothered about whether they are animated or not

**Comment by Jayflux** [comment]
Done some testing my side and it seems to be working ok

**Pull request merged**
