### PR TITLE
Update message formatting.

### PR DESCRIPTION
**Pull request by ehuss**
This contains two general changes for inline build messages.  The first addresses a problem with certain types of errors involving macro expansions causing exceptions and potentially lockups in the worst case.  The second is a set of updates to how messages are formatted.

I can try to split this into separate PRs, but many of the changes all touch the same part of the code.

I'm open to any suggestions to improving the appearance of the messages.

In detail:

* Add gutter icons for messages.
* Include links between the main message and sub-messages when they are located far away.
* Include notes about macro locations.
* Show notes and help in a different color.
* Don't repeat the message level for each line ("error", "warning", etc.).
* Show the "main" message first.
* Display the message left-aligned with the beginning of the line so it doesn't wrap past the right side so easily.
* Allow messages to word wrap if word wrapping is enabled.

Some examples of what the new messages look like:
image

image

image

image

image

### CODE REVIEW

**Comment by urschrei** [comment]
This looks like a fantastic set of changes to me, and improves the error ergonomics considerably. More generally, thanks for all the work you've put into improving rust-enhanced.

**Comment by ehuss** [comment]
@Jayflux, I was wondering if you have a chance to look at this.  I'm not sure if my PRs are too big, or if these changes aren't desired, or if you're just busy, or something else.

**Comment by Jayflux** [comment]
@ehuss I will try and take a look this week/weekend.
We could do with some more maintainers on this repo, i will speak to the rust-lang team about it

**Comment by Jayflux** [comment]
Just had a play with this, looks very good

**Comment by Jayflux** [comment]
Yup, looked good to me, ive put it in a new release https://github.com/rust-lang/sublime-rust/releases/tag/v2.2.0

Good work!

**Pull request merged**
