### PR TITLE
Major update

### PR DESCRIPTION
**Pull request by petrochenkov**
Since this package is not especially well maintained, I went forward and fixed everything I didn't like and considered a bug.

Digest:
- Snippets are moved to a separate subdirectory
- Some snippets fixed and many new ones are added, now they cover all popular language constructions
- Files are reformatted (no trailing spaces, new lines etc.) and generated files are regenerated
- Fixed some nested comments
- Fixed escapes in strings and characters, not all were highlighted
- List of keywords is updated, keywords are categorized
- List of primitive types is updated
- List of prelude types is updated
- Random types from libc are not highlighted specially anymore
- Numeric literals are fixed, in particular, float literals with exponent were horribly broken and octal - literals weren't processed at all
- Types, traits and variants are marked as `storage.type`, this is the most noticeable visual change (screenshots: [before](https://cloud.githubusercontent.com/assets/5751617/10353135/a54686fa-6d5c-11e5-9c43-8d8492eef8fd.png), [after](https://cloud.githubusercontent.com/assets/5751617/10353145/bd8b0e48-6d5c-11e5-9ba9-6f18cea24251.png) - they become blue in Monokai)
- Constants are marked as constants
- All the punctuation is highlighted
- Primitive modules (`std::u8`) are not marked as types

r? @brson

### CODE REVIEW

**Comment by petrochenkov** [comment]
Oh, and I can probably try to maintain this

**Comment by brson** [comment]
Badass :+1:

**Comment by c0gent** [comment]
Awesome work!

**Comment by petrochenkov** [comment]
@Jayflux, I see you have maintainer's rights now! Could you at last close all the ancient issues fixed by this ancient PR?

**Comment by Jayflux** [comment]
@petrochenkov Yup, doing that now

**Pull request merged**
