### PR TITLE
Export `RUST_BACKTRACE=1` for run/test/bench

### PR DESCRIPTION
**Pull request by alex-gulyas**

### CODE REVIEW

**Comment by dten** [comment]
this is really noisy for test / bench, maybe it could be a setting or something

**Comment by alex-gulyas** [comment]
I see 3 ways to make this configurable:

1. add "with backtrace" variants of bench and test (and maybe run?) to the cargo build system (easy, simple),
2. add a separate build system called "cargo with backtrace" (easy, simple, but I think its messy),
3. create a python module that manages the build system, and redirect the current build calls into it.

Obviously option 3 would be the best one, as it could offer more customization than enabling/disabling the backtrace mode, but I don't have the time to implement and test it.

**Comment by Jayflux** [comment]
@alex-gulyas  im sure this could be done via settings change no?
Similar to https://github.com/rust-lang/sublime-rust#syntax-checking

Anyway, you could need to re -up this PR as cargo.sublime-build has changed quite a bit

**Comment by Jayflux** [comment]
Closing

**Pull request closed without merging**
