### PR TITLE
Add syntax check support for projects with several build targets

### PR DESCRIPTION
**Pull request by Ostrovski**
Current implementation of syntax checking silently fails on cargo projects with several build targets (when there is `src/main.rs` and `src/lib.rs` at the same time or `src/bin/foo.rs`, `src/bin/bar.rs` and `src/lib.rs`). 

I've added customization support for `cargo rustc -- {target} -Zno-trans -Zunstable-options --error-format=json` command. One can affect on the `{target}` part via tweaking per-projects settings. 

Also since now the plugin writes explicit error message when `cargo rustc` command ends up with error.

### CODE REVIEW

**Comment by Jayflux** [comment]
I will try and test this when i get time

**Comment by Jayflux** [comment]
@Ostrovski is this a fix for https://github.com/rust-lang/sublime-rust/issues/94 ?

**Comment by Ostrovski** [comment]
@Jayflux yes, it is. The issue #94 was added a few days later my PR, so I didn't see it at that time. Have read comments on #94 and I think that using proposed in my PR "smart" target detector is better than just using cargo flags, because it's pretty expensive to check all targets at once.

**Comment by Jayflux** [comment]
@Ostrovski do you mind updating the documentation? Maybe adding it to the settings heading?
I've seen you've done it in the comments which is good, but just so people can find it in the readme

Thanks

**Comment by Ostrovski** [comment]
@Jayflux I've updated README.md in my fork, but it significantly changed it the main repo. I'll merge them on this weekend.

**Comment by Jayflux** [comment]
@Ostrovski thanks

**Comment by Ostrovski** [comment]
@Jayflux, I've updated the fork with the fresh master.

**Comment by Ostrovski** [comment]
@Jayflux, could you please remove this forgotten debug line? https://github.com/rust-lang/sublime-rust/blob/8cdb525a3d422c4cf7a25810d1378d8312b416ee/plugin.py#L14

**Pull request merged**
