### PR TITLE
New Cargo build system.

### PR DESCRIPTION
**Pull request by ehuss**
I wanted to share a WIP of a new, enhanced build system for Cargo.  I was wondering:
1. Would you would be willing to merge something like this?
2. Test it out and let me know what you think (any issues, ideas for improvements, etc.)

The main improvements are:
* Shows inline phantoms for errors/warnings when building.
* Properly handles cancelling/stopping a build.
* Pulls in the user's shell environment to make it less likely to have problems.
* Supports custom environment variables.
* Interacts more nicely with the on-save syntax checking.
* Allows you to configure settings for builds (see docs/build.md).
* Command to assist configuring custom build variants.
* On-save syntax checking supports different methods (rustc no-trans, cargo check, clippy)

This also closes a few issues: #182, #170, #162, #154, #146, #109

It should be fully functional in its current state, but I still have a long todo/improvement list.  Here's a copy in case you are curious:

- [x] Support custom build variants (passing in any and all settings).
   - [x] Also include interactive command to configure a new variant.
   - [x] Include "environment", and "path"
   - [x] Any custom arguments.
   - [x] working_dir
- [x] Set "default" project path/package.
- [x] Cargo "Automatic"
- [x] Add "--features" support.
- [x] cargo check
- [x] test: Message-order: Next/Prev testing
    Test with a variety of message types (to ensure is_main is good)
    Test with already open files and files that need to be opened.
- [x] Test without cargo manifest
- [x] Test without sublime project
- ~~[ ] Run with multiple executables displays this error:
        error: `cargo run` requires that a project only have one executable; use the `--bin` option to specify which one to run
  Should we detect this, and bring a popup to select a target?~~ Deferred
- [ ] Clippy:  Should it automatically use nightly toolchain?
    - [ ] Same with Bench?
- [x] Make links in clippy output clickable.
- [x] Deal with duplicate messages generated by clippy  (filter duplicate messages in general)
- [x] Make clippy an option for on-save checking.
- [x] Should the cargo settings be used for SyntaxCheck somehow?
- ~~[ ] I think the build-language could be improved (coloring file filenames, numbers, etc.)~~ Deferred
- ~~[ ] Something similar to Anaconda Show Errors (popup with list of errors)~~ Deferred
- ~~[ ] Other cargo test options?: --doc --no-run --no-fail-fast~~ Deferred
- [x] Is term "Target" too confusing?   Filter or Kind?
    Internally Cargo uses various terms (CompilerFilter, Kind, Target)
- [x] Update README
- [x] Fix called with multiple buffers (views) into same file. (Terminates, but otherwise runs correctly.  This is something that really needs to be fixed in Sublime.)
- [x] Check setting "show_errors_inline"?  In case someone doesn't like the phantom style.
- [x] Possibly consolidate the configuration commands into a single command?
- [x] Add command to configure environment variables (in particular, make it easy to add RUST_BACKTRACE=1).

One last thing, this replaces the "rustc" build variants.  I'm not sure what the use case is for those, and whether or not "cargo script" is a sufficient replacement.

### CODE REVIEW

**Comment by Jayflux** [comment]
I agree about the "rustc" build variants, they're not really needed now we have Cargo Script. So im fine with that

**Comment by Jayflux** [comment]
Looks like there could be some big, potentially breaking changes in this (especially if rust build is being removed)

So marking as a potential for 2.0.0 for now

**Comment by ehuss** [comment]
@Jayflux I was wondering if you still might be interested in integrating this.  The only critical change still pending is updating the README.  I would be happy to have some feedback about it, particularly things that could be improved or changed.

**Comment by Jayflux** [comment]
Hi @ehuss, I'm currently on holiday at the moment but back next week.
I'm happy to pull this down and go through the changes you've made and see if we can integrate it as a 2.0.0 release. Would be worth hearing @dten s thoughts too

**Comment by Jayflux** [comment]
@ehuss  im back now, how did you want this reviewed?

**Comment by ehuss** [comment]
Good question.  I don't have anything else left that I am planning to do, so it should be ready to go.

I think primarily testing it out and seeing if you have any obvious problems.  I've tested on Windows, Mac, and Linux, but it always helps to try on someone else's setup.  See if the usage and documentation make sense and is not too confusing.

I have not yet switched the default on-save syntax check to `cargo check`.  I'm currently running with `check` on my systems, and it seems to be fine (aside from not handling `#[test]`).

**Comment by Jayflux** [comment]
Not ignoring this just been pretty busy, and maybe this weekend too.
So will try and check this next week

**Comment by Jayflux** [comment]
Sorry this has taken a while, I've been away on holiday

Been taking a look at this today, first off great work, I like the documentation you've added around Cargo build and i like the addition of Automatic.
Having a single build system (instead of Rust build and Cargo build) is much better too.

Everything still seems to work fine from my end and nothing is broken.

When i click "Configure Cargo Build" then "Set Target", it sends me to a build menu, like "Automatic", "Bench", "Check" is it supposed to do this?

When attempting to add an environment variable it opens a new window (with RUST_BACKTRACE: 1 already in it commented out) if i type nothing and try to close the windows sublime text crashes, does this happen for you? (ST3 3126) Windows 10

**Comment by ehuss** [comment]
The "Set Target" sets the default target per build variant.  So if you want to run just 1 test file, you choose "Test > Test: test_name".  Then when you run the "Test" variant, it always uses that target.  I felt like it didn't make sense to have a global default target since targets are often specific to a particular variant.  I think it would be nice if it would only show targets for the currently active build variant, but AFAIK it is not possible to ask Sublime which is currently active.

Yes, you found a bug with the environment variables.  I just pushed a fix, thanks!

**Comment by Jayflux** [comment]
@ehuss can i help with any of these items to speed things up?

**Comment by ehuss** [comment]
The remaining unchecked items are mostly nice-to-haves or random thoughts.  I'll go through and clear out what's left and add a few more tests.  I guess the only issue I was really uncertain about is:

Should Clippy and Bench default to running on nightly?  Clippy *should* work correctly without that if you have your PATH/LD_LIBRARY_PATH set correctly, but I assume most people don't do that (it would be nice if that was fixed in rustup).  Also, if clippy is later distributed as a rustup component, it won't be necessary.  I have no idea what the future holds for "bench".

**Comment by urschrei** [comment]
Just wondering how we feel about merging this?

**Comment by ehuss** [comment]
I'm ready for it to be merged and to address any issues that crop up.

**Comment by Jayflux** [comment]
Hi guys, I've been a way lately but should have some time next week to look at this, and hopefully we can get a 2.0.0 release going with this in

**Comment by Jayflux** [comment]
Im hopefully going to give this a final check this weekend, but before i do it would be great if @urschrei or @dten could give some feedback before we merge.

Jase

**Comment by Jayflux** [comment]
Looks good to me, merged

**Comment by urschrei** [comment]
Amazing. Thanks @Jayflux and @ehuss for putting all this work in.

**Pull request merged**
