### PR TITLE
Syntax changes with aim of improving consitency

### PR DESCRIPTION
**Pull request by dten**
#113 raises a good point about consitency so I've made some changes but would like some feed back. (don't merge this without discussion please)

if @boscop or @petrochenkov would like to give comment that would be appreciated

currently function calls aren't highlighted, i got stuck trying to make generic function calls match the non generic ones so gave up and went with white for all functions calls for consitency

### CODE REVIEW

**Comment by Boscop** [comment]
Do you have an example screenshot how it looks like now?

**Comment by dten** [comment]
the thing is there's also consistency at the sublime level. Most syntaxes have function declarations appear green but calls are white (in monokai). This is even visible from the front page  https://www.sublimetext.com

I'll put together some screenshots but they won't be able to show everything. I'll probably steal your snippets :) If you can use git to add get the pr version of the plugin that would help see more.

**Comment by dten** [comment]
http://www.sublimetext.com/docs/3/scope_naming.html

Explains some choices. I hadn't noticed this doc though so I'll see how it compares.

**Comment by petrochenkov** [comment]
I'll try to read the patch, but I need to read the scope naming docs first (also, screenshots would be nice).
Some screen of the previous scheme (in Monokai) for reference: https://cloud.githubusercontent.com/assets/5751617/10353145/bd8b0e48-6d5c-11e5-9ba9-6f18cea24251.png, this is https://github.com/rust-lang/rust/blob/master/src/librustc/ty/mod.rs#L1258

**Comment by Boscop** [comment]
Why not use that Monokai color scheme? It's very consistent.

**Comment by dten** [comment]
this is that code with my changes (the latest version anyway)
image

the impl target shows green but you can `goto` it which is the price to pay

i'd like to get the functions blue but i haven't got a reliable way to do it yet

@Boscop the plugin doesn't directly use monokai. the plugin defines the scopes as per my link above. the colour schemes then choose to highlight certain scopes with certain colours

**Comment by dten** [comment]
another comparison using tha tcode 

`PR`
image

`v1.0.1`
image

`v1.0.0`
image

pre change:
image

**Comment by Jayflux** [comment]
@dten correct me if im wrong but looks like you're fixing https://github.com/rust-lang/sublime-rust/issues/61 too

**Comment by wbond** [comment]
A bunch of these changes are done in opposition to the way that we are standardizing Sublime Text packages.

For instance, to include symbols in the symbol list, you need to add the scope to the `.tmPreferences` file, not change the scope names.

Effectively this will orphan this package from the official package is was just forked from, and undoes a lot of work done to make it more consistent. Ideally we could move thing forward towards more consistency. I realize this takes time and work, since Sublime Text needs to care about consistency of all default syntaxes, not just the preferences of users who primarily work in Rust.

Let me know if you'd like me to provide specific feedback about where things are going against the grain, and I will take the time. Otherwise, I'm let you make your choices. Ideally, however, the syntax should no longer be called `Rust`, but rather something like `Rust Improved`, or something like that. This help in debugging issues opened on the official issue tracker and in the forum.

**Comment by wbond** [comment]
Sorry, I just noticed the syntax name has already been made.

**Comment by Jayflux** [comment]
@wbond, could you elaborate on where we're going against the grain? I would love to hear some specific feedback on this change to make sure we're not going too far off track.

I will look into scope names.
And yes the syntax has changed to Rust Enhanced since version 1.0.0

**Comment by dten** [comment]
thanks for the tips @wbond I hadn't noticed the standardising doc at the time. I don't have time today but I'm gonna go through it and try make this more standard and use the symbols settings properly
being consistent with sublime even if it's "enhanced" is definitely important

**Comment by dten** [comment]
@Jayflux can you tag this `WIP` or `do-not-merge` or something

**Comment by Boscop** [comment]
@dten It already looks much better. The things I would add is, :,::,<,>,;,-> should be red, too. And function arg names should be white IMHO, like in that screenshot that @petrochenkov showed. So that for the eye it's easier to match the names with the same names occuring in the function body. (Maybe self should be orange at all times.)
I think it would be great if we can match what Monokai does.

**Comment by wbond** [comment]
@Jayflux Reading http://www.sublimetext.com/docs/3/scope_naming.html would be the most useful in terms of understanding where you are going against the grain. I will highlight below some of the things I noticed by quickly reviewing some of the commits.

`entity.name.type.{label}` is deprecated in favor of `entity.name.{label}`.

`impl` and `fn` should be `storage.type`. There has been some discussion around changing this, but the current standard is `storage.type` instead of `keyword`. This is pulling from the original Textmate docs. There have been arguments back and forth about a new `keyword.` variant to handle such keywords. I think it is likely it will change at some point, but we haven't had enough input to finalize where we'd like to change the conventions. More at https://github.com/sublimehq/Packages/issues/582.

`entity.name.label` is the canonical "label" scope.

In syntaxes where function call syntax is consistently identifiable (e.g. languages more like JavaScript than Ruby), we are adding the scope `support.function`. Ideally if a user doesn't want that highlighted, they can change their color scheme.

Is a `.` really an operator? Usually languages use these as some sort of accessor, so it should get `punctuation.accessor`, not `keyword.operator`.

Ideally we'd love to pull improvements into the default syntax. As long as they don't break our conventions, and you are willing, I will plan on trying to merge them in the next time I work on the default packages.

**Comment by wbond** [comment]
Also, I recommend you try to not get too hung up on the color of certain tokens since that is 100% controlled by the color scheme. The syntax is really mean to add semantic scopes to the tokens so they can be used for syntax highlighting with the color scheme, but also for targeting preferences and allowing plugins to target specific tokens for advanced editing features.

**Comment by dten** [comment]
@wbond it does get a bit disappointing though when you put lots of work into making it correct and it just ends up all highlighted white 👍 🤕

**Comment by wbond** [comment]
@dten Well, the color scheme can be improved too! I'm happy to try and make improvements to the docs to aide that process. So far there is some guidance at the bottom of the Scope Naming docs. Perhaps one of the next steps is for me to specifically reach out to developers of the more popular color schemes and try to get them to include support?

As part of the work I've been doing on the standard packages, my plans in the somewhat near term include revamping the built-in colors schemes so we only include those that have good coverage of the standard scopes. It won't be a quick process, but writing the docs I linked to are the first step in spreading the word about how we are trying to push forward improvements for ST users. Too long has writing syntaxes and color schemes been a process fraught with poor documentation and fragmentation.

**Comment by Jayflux** [comment]
@dten i don't seem to have permissions to adjust Labels or Milestones, :/

**Comment by Jayflux** [comment]
@dten how are things going with this?

**Comment by Jayflux** [comment]
@dten whats happening with this?

**Comment by dten** [comment]
i'm a bit burnt out to be honest. i went round in circles a bit locally not wanting to undo wbond's intentions but wasn't happy with how it actually highlights.

**Comment by Jayflux** [comment]
@dten are you on irc or somewhere for more instant chat?

**Comment by wbond** [comment]
If you aren't happy with how it highlights, then the color scheme needs to be updated

**Comment by dten** [comment]
Where are they hiding?

**Comment by Jayflux** [comment]
@dten 
Scope Naming: https://www.sublimetext.com/docs/3/scope_naming.html
The built in color scheme however looks closed source, i don't see any reference to it

**Comment by wbond** [comment]
> I wonder if its possible to override the default scheme?

Every user can pick their own color scheme. You can't "override" the default color scheme unless the user places a new version at `Packages/Color Scheme - Default/Monokai.tmTheme`.

In general, with the default color scheme (Monokai) we aim for consistency. There shouldn't be much of anything in terms of syntax-specific highlighting rules. I would imagine most other color schemes are going to do the same thing. *However, Jon does have the final say in how he wants Monokai to highlight, and has tweaked things for C/C++ in the past.*

Overall, the syntax really needs to be accurate, within the scope naming guidelines.

You could certainly ship your own color scheme focused on the Rust Enhanced syntax, I know where were some JS packages that did that for a while. In the end the users will pick what they want for a syntax and color scheme.

> The built in color scheme however looks closed source

We don't have it on GitHub since we don't currently think that is makes sense to accept patches for it. Color schemes are largely preference driven, and there are hundreds available at https://packagecontrol.io/. It is trivial for a user to copy one of the defaults and tweak it to what they would like.

Syntaxes, however, are interdependent, and are much less subjective. They either properly recognize constructs or not. The scope names are subjective, which is why we've published docs on using standard scope names. That way color scheme authors can expect reasonable results and not have to research the scope names used in a bunch of the popular syntaxes.

----

Personally, I'd appreciate any bugs you find with the build-in Rust syntax reported at https://github.com/sublimehq/Packages/issues. We want to ship complete support for Rust. We have a group of people who are experts at writing `.sublime-syntax` definitions at the Packages repo, and I can add features and make fixes to the engine. What we don't have is experts in Rust syntax and many frequent users.

That said, different users will have different preferences in terms of how they want things to look. Hopefully creating a special color scheme will make more sense for most users than maintaining a new syntax. For the situations when it isn't, you can certainly ship a custom syntax like you've done with this package.

**Comment by Jayflux** [comment]
@wbond thanks for taking the time to reply
I would appreciate your guidance on what I should do with https://github.com/rust-lang/sublime-rust/issues/51

**Comment by dten** [comment]
i'm not sure there's much left to salvage from this, @Jayflux so gonna close it. i think we've got what it had through other prs

**Pull request closed without merging**
