### PR TITLE
Add configurable colors for syntax checker

### PR DESCRIPTION
**Pull request by ark-**
Allows users to select a colour which works with their given color scheme.

Fixes issue #102

### CODE REVIEW

**Comment by Jayflux** [comment]
@ark- could you re-do this? The name of the plugin file has changed

**Comment by ark-** [comment]
Merged your new changes into my build. Should be good now.

**Comment by ark-** [comment]
Worth noting if the user has no settings string for colour then I used the predefined variables defined here: http://www.sublimetext.com/docs/3/minihtml.html#variables

The look of these phantoms could do with some work, I have trialed a version with bold underlines and coloured backgrounds on my local version of the plugin which I like (see below). If you're interested we could investigate further in a separate PR.

image

image

**Comment by Jayflux** [comment]
@ark- I will try and test this, this week

**Comment by Jayflux** [comment]
@ark- just tested this, looks good 👍

**Pull request merged**
