### PR TITLE
Fix and enhance next/prev message jumping.

### LINKED ISSUE #199: Should jump to first error even when there are warnings
When I get some warnings and some errors during a build and I press F4, it should jump to the first error (and then step from there).
Currently it jumps to the first warning which is often something trivial like `unused import`.
This behavior is annoying, I want to fix the errors first because they have higher priority...

(IIRC it used to be the case that F4 jumps to the first error in the past, but maybe I remember wrong.)

### LINKED ISSUE #206: Next Result / Previous Result (F4 / Shift + F4) don't work when "show_errors_inline" is false
Some people might prefer to disable inline errors (myself included), but that breaks the "Next Result" and "Previous Result" commands. My guess is that it happens because the non-inline error output doesn't conform to the pattern that Rust Enhanced expects. 

This is how the error output looks like:
```
error[E0425]: cannot find function `helo` in this scope
 --> src/main.rs:3:5
  |
3 |     helo()
  |     ^^^^ did you mean `hello`?
```
Problem is probably the `-->` thing at the beginning of the line.

I was trying to fix this by adding a custom `file_regex` entry to `Rust Enhanced.sublime-build`, but it didn't work because the custom command used (`cargo_exec`) doesn't recognize that option.

### LINKED ISSUE #209: Find in Files: Next Result / Previous Result shortcuts (F4 / Shift + F4) broken
The default shortcuts to navigate the find results of "Find in Files" (F4 and Shift + F4) do not work when Rust Enhanced is in effect. I suspect this is because Rust Enhanced redefines them to trigger the "rust_next_message" and "rust_prev_message" actions. Not sure what those actions do in addition to the default next_result / prev_result, but maybe they should just fall back to the default behavior when "Find in Files" is in effect?

### PR DESCRIPTION
**Pull request by ehuss**
This contains a set of fixes and enhancements for the next/prev message commands:

* Sort messages so that errors show up before warnings (fixes #199).
* Fix next/prev when `show_errors_inline` is false (fixes #206).
* Fix on-save checking when `show_errors_inline` is false.
* Scroll the build output panel on next/prev message.
* Next/prev now cycles through test errors.
* Fix Next/Prev overriding find-in-files next/prev (fixes #209).

These changes depend on the changes in #201.

### CODE REVIEW

**Comment by dten** [comment]
i tried this branch cause i wasn't getting F4 etc but for me from commit 7d1ec57a03aa0e92f157bc79186c253e5a8f58fb I get these messages and then build says `Unable to find target command: cargo_exec`

```
reloading plugin Rust Enhanced.cargo_build
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\cargo_build.py", line 6, in <module>
    from .rust import (rust_proc, rust_thread, opanel, util, messages,
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\rust\opanel.py", line 6, in <module>
    from . import rust_proc, messages, util
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\rust\messages.py", line 13, in <module>
    from . import util, opanel
ImportError: cannot import name opanel
reloading plugin Rust Enhanced.SyntaxCheckPlugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\SyntaxCheckPlugin.py", line 4, in <module>
    from .rust import (messages, rust_proc, rust_thread, util, target_detect,
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\rust\messages.py", line 13, in <module>
    from . import util, opanel
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\DavidHewson\AppData\Roaming\Sublime Text 3\Packages\Rust Enhanced\rust\opanel.py", line 6, in <module>
    from . import rust_proc, messages, util
ImportError: cannot import name messages
```

**Comment by dten** [comment]
is it cause `messages` imports `opanel` and `opanel` imports `messages`?

**Comment by dten** [comment]
i deferred the imports and it seems to be working now

**Comment by ehuss** [comment]
Thanks for taking a look at it.  I guess I never restarted Sublime (and I even tested it on multiple systems). ☹️   And sorry for breaking things, I wasn't considering all the use cases.  Please let me know if there are any other issues.

**Comment by dten** [comment]
Only niggle was it doesn't always show messages for test code

**Comment by ehuss** [comment]
Do you mean error messages for the on-save checking?  If so, that is still blocked on rust-lang/cargo#4039.  

If it is something else, can you show an example?

**Comment by ehuss** [comment]
I rebased this off master now that #201 has been merged.

**Comment by Boscop** [comment]
Any update on this?
(Jumping to errors before warnings is very important for me..)

**Comment by Jayflux** [comment]
Should be able to get this into the next release @Boscop

**Pull request merged**
